### ISSUE TITLE
Use DataEntity for formatting and error handling

### ISSUE THREAD

**Issue by peterdemartini** [terascope/chunked-file-reader#8]
`getChunk` should use the DataEntity formatting. Additionally, it should try and follow the `_bad_record_action` supported by the framework, see this [example](https://github.com/terascope/kafka-assets/blob/fixes-to-1.2.x/asset/teraslice_kafka_reader/index.js#L262-L276). Although this won't support anny custom actions supported by the framework.

**Comment by macgyver603** [comment]
This is addressed by #9
